apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: edge-server-deploy
  labels:
    app: edge
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
        - name: edge-server
          image: edge-image:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: edge-server-service
  labels:
    app: edge
spec:
  selector:
    app: edge
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
